MVCDatabaseFirstProject_TrainingAcademy/Models/Trainer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDatabaseFirstProject_TrainingAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int TrainerId { get; set; }
        public string TrainerName { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}

MVCDatabaseFirstProject_TrainingAcademy/Models/ViewModel/TrainerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCDatabaseFirstProject_TrainingAcademy.Models.ViewModel
{
    public class TrainerViewModel
    {
        [Key]
        [Display(Name = "Trainer Id")]
        public int TrainerId { get; set; }
        [DataType(DataType.Text)]
        
        [Display(Name = "Trainer Name")]
        public string TrainerName { get; set; }
       
        [Display(Name = "Phone")]
        public string PhoneNumber { get; set; }
    }
}

MVCDatabaseFirstProject_TrainingAcademy/Controllers/TrainerController.cs
using MVCDatabaseFirstProject_TrainingAcademy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCDatabaseFirstProject_TrainingAcademy.Controllers
{
    public class TrainerController : Controller
    {
        DBFirstTrainingDBEntities dbobj = new DBFirstTrainingDBEntities();
        // GET: Trainer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateTrainerAjax()
        {
            var Model = dbobj.Trainers.ToList();
            return View(Model);
        }
        public ActionResult TrainerAjaxFormExample(Trainer obj)
        {
            
            dbobj.Trainers.Add(obj);
            dbobj.SaveChanges();
            IEnumerable<Trainer> list = dbobj.Trainers.ToList();
            return View(list);
        }
    }
}

MVCDatabaseFirstProject_TrainingAcademy/Views/Trainer/CreateTrainerAjax.cshtml
@model IEnumerable<MVCDatabaseFirstProject_TrainingAcademy.Models.Trainer>
@{
    ViewBag.Title = "CreateTrainerAjax";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<script src="~/Scripts/jquery-3.3.1.min.js"></script>*@
<script src="~/Scripts/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

<div class="container-fluid">
    <div class="col-md-5 mx-auto my-5">
        <div id="divAjax1">
            @using (Ajax.BeginForm("TrainerAjaxFormExample", "Trainer", new AjaxOptions
            {
                UpdateTargetId = "divAjax",
                HttpMethod = "POST",
                Confirm = "Are you sure to Save this Data?",
                LoadingElementId = "LoadingImage",
                LoadingElementDuration = 3000,
                OnComplete = "Clear",
            }))
            {
                @Html.AntiForgeryToken()

                <h2 class="text-center">Create Trainer</h2>
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                <div class="form-group mb-3">
                    @Html.Label("Trainer Name", new { @class = "form-label" })
                    @Html.TextBox("TrainerName", null, new { @class = "form-control" })
                </div>
                <div class="form-group mb-3">
                    @Html.Label("Phone Number", new { @class = "form-label" })
                    @Html.TextBox("PhoneNumber", null, new { @class = "form-control" })
                </div>
                <div class="form-group mb-3">
                    <input type="submit" value="Save" class="btn btn-lg btn-info" />
                </div>
                <div class="col-md-12" id="LoadingImage" style="display:none;">
                    <img src="~/App_Images/redballLoading.gif" width="200" height="100" />
                </div>

            }
        </div>
        <div id="divAjax">
            @{Html.RenderPartial("_TrainerListView", Model);}
        </div>
    </div>
</div>

MVCDatabaseFirstProject_TrainingAcademy/Views/Trainer/TrainerAjaxFormExample.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TrainerAjaxFormExample</title>
</head>
<body>
    <div>
        <table class="table table-bordered table-striped">
            <tr>
                <th>Trainer ID</th>
                <th>Trainer Name</th>
                <th>Phone</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.TrainerId</td>
                    <td>@item.TrainerName</td>
                    <td>@item.PhoneNumber</td>
                </tr>
            }
        </table>
    </div>
</body>
</html>