MVCDatabaseFirstProject_TrainingAcademy/Models/Training.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDatabaseFirstProject_TrainingAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Training()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int TrainingId { get; set; }
        public string TrainingName { get; set; }
        public decimal TrainingCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
    }
}

MVCDatabaseFirstProject_TrainingAcademy/Models/ViewModel/TrainingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCDatabaseFirstProject_TrainingAcademy.Models.ViewModel
{
    public class TrainingViewModel
    {
        [Key]
        [Display(Name = "Training Id")]
        public int TrainingId { get; set; }
        
        [DataType(DataType.Text)]
        [Display(Name = "Training Name")]
        public string TrainingName { get; set; }
        
        [Display(Name = "Training Cost/Hour")]
        public decimal TrainingCost { get; set; }
    }
}

MVCDatabaseFirstProject_TrainingAcademy/Controllers/TrainingController.cs
using MVCDatabaseFirstProject_TrainingAcademy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCDatabaseFirstProject_TrainingAcademy.Controllers
{
    public class TrainingController : Controller
    {
        DBFirstTrainingDBEntities dbobj = new DBFirstTrainingDBEntities();
        // GET: Training
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateTrainingAjax()
        {
            var Model = dbobj.Trainings.ToList();
            return View(Model);
        }
        public ActionResult TrainingAjaxFormExample(Training obj)
        {
            
            dbobj.Trainings.Add(obj);
            dbobj.SaveChanges();
            IEnumerable<Training> list = dbobj.Trainings.ToList();
            return PartialView(list);
        }
    }
}

MVCDatabaseFirstProject_TrainingAcademy/Views/Training/CreateTrainingAjax.cshtml
@model IEnumerable<MVCDatabaseFirstProject_TrainingAcademy.Models.Training>
@{
    ViewBag.Title = "CreateTrainingAjax";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>


<div class="container-fluid">
    <div class="col-md-5 mx-auto my-5">
        <div id="divAjax1">
            @using (Ajax.BeginForm("TrainingAjaxFormExample", "Training", new AjaxOptions
            {
                UpdateTargetId = "divAjax",
                HttpMethod = "POST",
                Confirm = "Are you sure to Save this Data?",
                LoadingElementId = "LoadingImage",
                LoadingElementDuration = 3000,
                OnComplete = "Clear",
            }))
            {
                @Html.AntiForgeryToken()

                <h2 class="text-center">Create Training</h2>
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                <div class="form-group mb-3">
                    @Html.Label("Training Name", new { @class = "form-label" })
                    @Html.TextBox("TrainingName", null, new { @class = "form-control" })
                </div>
                <div class="form-group mb-3">
                    @Html.Label("Training Cost", new { @class = "form-label" })
                    @Html.TextBox("TrainingCost", null, new { @class = "form-control" })
                </div>
                <div class="form-group mb-3">
                    <input type="submit" value="Save" class="btn btn-lg btn-info" />
                </div>
                <div class="col-md-12" id="LoadingImage" style="display:none;">
                    <img src="~/App_Images/redballLoading.gif" width="200" height="100" />
                </div>

            }
        </div>
        <div id="divAjax">
            @{Html.RenderPartial("_TrainingListView", Model);}
        </div>


    </div>
</div>
<script>
    function Clear() {
        $(this).closest('form').find("input[type=text], textarea").val("");
    }
</script>

MVCDatabaseFirstProject_TrainingAcademy/Views/Training/TrainingAjaxFormExample.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TrainingAjaxFormExample</title>
</head>
<body>
    <div>
        <table class="table table-bordered table-striped">
            <tr>
                <th>Training ID</th>
                <th>Training Name</th>
                <th>Training Cost</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.TrainingId</td>
                    <td>@item.TrainingName</td>
                    <td>@item.TrainingCost</td>
                </tr>
            }
        </table>
    </div>
</body>
</html>